modLoader = "javafml"
loaderVersion = "[46,)"
license="${mod_license}"

[[mods]]
modId = "additional_attributes"
displayTest="IGNORE_ALL_VERSION"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "minecraft:book"

[[dependencies.additional_attributes]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.additional_attributes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.additional_attributes]]
modId = "irons_spellbooks"
mandatory = false
versionRange = "[1.20.1-2,)"
ordering = "AFTER"
side = "BOTH"